CREATE TABLE IF NOT EXISTS USERS (
    ID SERIAL PRIMARY KEY
    , USERNAME  VARCHAR(100)
    , EMAIL     VARCHAR(255) UNIQUE NOT NULL
    , PASSWORD  VARCHAR(100) NOT NULL
    , CREATED   TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ROLES (
    ID SERIAL PRIMARY KEY
    , NAME VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS USER_ROLES (
    USER_ID      INT NOT NULL
    , ROLE_ID    INT NOT NULL
    , CREATED_ON TIMESTAMP
    , PRIMARY KEY(USER_ID, ROLE_ID)
    , FOREIGN KEY(ROLE_ID) REFERENCES ROLES(ID)
    , FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);