CREATE TABLE IF NOT EXISTS BOOK_IMAGES (
    BOOK_ID      INT NOT NULL
    , IMAGE_ID   INT NOT NULL
    , CREATED_ON TIMESTAMP
    , PRIMARY KEY(BOOK_ID, IMAGE_ID)
    , FOREIGN KEY(BOOK_ID)  REFERENCES BOOKS(ID)
    , FOREIGN KEY(IMAGE_ID) REFERENCES IMAGES(ID)
);

CREATE TABLE IF NOT EXISTS USER_IMAGES (
    USER_ID      INT NOT NULL
    , IMAGE_ID   INT NOT NULL
    , CREATED_ON TIMESTAMP
    , PRIMARY KEY(USER_ID, IMAGE_ID)
    , FOREIGN KEY(USER_ID)  REFERENCES USERS(ID)
    , FOREIGN KEY(IMAGE_ID) REFERENCES IMAGES(ID)
)